spring:
  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:kanban
    username: sa

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true