spring:
  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:kanban
    username: sa

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  header: Authorization
  secret: UHJvamVjdCBVbmRlciBDb250cm9sIHdpdGggS2FuYmFuIEJvYXJk
  expiration:
    access : 1800
    refresh : 604800

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG